spring:
  datasource:
    url: ${env.DATABASE_URL:jdbc:postgresql://localhost:5432/personal-property}
    username: ${env.DATABASE_USER:postgres}
    password: ${env.DATABASE_PASS:pass}
  dbcp2:
    max-wait-millis: 30000
    validation-query: SELECT 1
    validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  security:
    ignored:
      - "*.bundle.*"
    user:
      name: ${env.SECURITY_USER:user}
      password: ${env.SECURITY_PASS:pass}
  bucket4j:
    enabled: true
    filters:
      - cache-name: buckets
        url: /*
        rate-limits:
          - bandwidths:
              - capacity: 5
                time: 10
                unit: seconds
springdoc:
  pathsToMatch: /api/**
