package com.claytonmasterson.personal_property.model;

import lombok.Getter;
import lombok.Setter;

/**
 * This is boilerplate code generated by Bootify.io
 */

@Getter
@Setter
public class FieldError {

    private String field;
    private String errorCode;

}
