package com.claytonmasterson.personal_property.model;

import java.util.UUID;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;

/**
 * This is mostly boilerplate code generated by Bootify.io
 * My changes are notated below.
 */

@Getter
@Setter
public class InsuredItemDTO {

    private UUID id;

    @NotNull
    @Size(max = 255)
    private String name;

    @Size(max = 128)
    private String productCode;

    /**
     * I changed the DTO datatype to String
     */
    private String productType;

    @Size(max = 255)
    private String authorArtist;

    private Integer releaseYear;

    private Double estimatedValue;

    private String description;

}
