package com.claytonmasterson.personal_property.domain;

import com.claytonmasterson.personal_property.model.ProductType;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.util.UUID;

/**
 * This is boilerplate code generated by Bootify.io
 */

@Entity
@Getter
@Setter
public class InsuredItem {

    @Id
    @Column(nullable = false, updatable = false, columnDefinition = "UUID")
    @GenericGenerator(name = "uuid", strategy = "org.hibernate.id.UUIDGenerator")
    @GeneratedValue(generator = "uuid")
    private UUID id;

    @Column(nullable = false)
    private String name;

    @Column(length = 128)
    private String productCode;

    @Column
    @Enumerated(EnumType.STRING)
    private ProductType productType;

    @Column
    private String authorArtist;

    @Column
    private Integer releaseYear;

    @Column
    private Double estimatedValue;

    @Column(columnDefinition = "text")
    private String description;

}
